### ISSUE TITLE
the plugin does not work at 90%

### ISSUE THREAD

**Issue by Mr1rbis** [SuchByte/Macro-Deck-Twitch-Plugin#7]
Several functions that I use don't work in the plugin:
1) Sending messages in twitch chat
2) Changing the name and activity of the broadcast does not work, I have not looked at other functions, but I can assume that they also do not work, except for cheating subscribers, cheating emoticons, cheating subscribers in the chat.

**Comment by manuelmayer-dev** [comment]
Fixed with v1.0.2
